### ISSUE TITLE
Error in gmfd_kmeans

### ISSUE THREAD

**Issue by lorebon** [cran/gmfd#1]
I want to compute the K-Means algorithm on a multivariate functional dataset, and I've met the following error while using the function `gmfd_kmeans(funData)`: 

> "Error in data.frame(..., check.names = FALSE) : 
>   gli argomenti implicano un numero differente di righe: 0, 1474"

I've done some debugging and I found out that, in your source code `kmeans.R` at line 95:

`xR <- NULL
   for ( r in 1:R )
xR <- cbind( xR, data[[r]] )`

the algorithm tries to column-bind a 0-length vector and a matrix with n-rows and m-columns, and it fails.

If I change the above lines to:

`xR <- data[[1]]
  for ( r in 2:R )
    xR <- cbind( xR, data[[r]] )`

initializing 'xR' to the first element of the dataset, the error does not pop out.

Am I doing something wrong? Did I forgot to pre-process data or something else?

Thanks in advance for your support.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
